// Placeholder menu used when Supabase is unreachable or not configured yet, so
// the customer screens are demonstrable before the admin panel exists. Content
// mirrors the wireframes; real prices/taxonomy still need confirming with the
// vendor (PRD §11). Shape matches what normaliseMenu() produces from Postgres.
export const SEED_CATEGORIES = [
  { id: 'small-chops', name: 'Small Chops' },
  { id: 'grills', name: 'Grills' },
  { id: 'trays', name: 'Platters/Trays' },
  { id: 'drinks', name: 'Drinks' },
]

export const SEED_ITEMS = [
  {
    id: 'puff-puff',
    categoryId: 'small-chops',
    name: 'Puff Puff (6pc)',
    description: 'Soft fried dough bites',
    price: 800,
    imageUrl: null,
    isAvailable: true,
    variants: [],
  },
  {
    id: 'chicken-samosa',
    categoryId: 'small-chops',
    name: 'Chicken Samosa',
    description: 'Spiced chicken filling',
    price: 1200,
    imageUrl: null,
    isAvailable: true,
    variants: [],
  },
  {
    id: 'spring-rolls',
    categoryId: 'small-chops',
    name: 'Spring Rolls',
    description: 'Veg & chicken mix',
    price: 1000,
    imageUrl: null,
    isAvailable: true,
    variants: [],
  },
  {
    id: 'suya-skewers',
    categoryId: 'grills',
    name: 'Suya Skewers',
    description: 'Beef, yaji spice, onions',
    price: 2500,
    imageUrl: null,
    isAvailable: true,
    variants: [],
  },
  {
    id: 'peppered-wings',
    categoryId: 'grills',
    name: 'Peppered Chicken Wings',
    description: 'Six wings, house pepper sauce',
    price: 3000,
    imageUrl: null,
    isAvailable: true,
    variants: [],
  },
  {
    id: 'combo-tray',
    categoryId: 'trays',
    name: 'Small Chops Combo Tray',
    description: 'Mixed tray — puff puff, samosa, spring rolls, chicken wings.',
    price: null,
    imageUrl: null,
    isAvailable: true,
    variants: [
      { id: 'combo-20', label: 'Tray of 20', price: 3500, isAvailable: true },
      { id: 'combo-50', label: 'Tray of 50', price: 7000, isAvailable: true },
      { id: 'combo-100', label: 'Tray of 100', price: 12000, isAvailable: true },
    ],
  },
  {
    id: 'grill-platter',
    categoryId: 'trays',
    name: 'Grill Platter',
    description: 'Suya, wings and gizzard on one board',
    price: null,
    imageUrl: null,
    isAvailable: true,
    variants: [
      { id: 'platter-small', label: 'Small', price: 9000, isAvailable: true },
      { id: 'platter-large', label: 'Large', price: 16000, isAvailable: true },
    ],
  },
  {
    id: 'zobo',
    categoryId: 'drinks',
    name: 'Zobo Drink',
    description: 'Chilled hibiscus, lightly spiced',
    price: 500,
    imageUrl: null,
    isAvailable: true,
    variants: [],
  },
  {
    id: 'chapman',
    categoryId: 'drinks',
    name: 'Chapman',
    description: 'House mix, served by the bottle',
    price: 1500,
    imageUrl: null,
    isAvailable: false,
    variants: [],
  },
]
